#!/usr/bin/env node

/**
 * Server Build Script
 * Uses esbuild to bundle the TypeScript server into a single CJS file
 * 
 * Best Practices Applied:
 * - External packages for Node.js native modules
 * - Proper ESM to CJS conversion
 * - Source maps for debugging
 * - Banner for require compatibility
 * - Error handling with clear messages
 */

import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs/promises';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const config = {
  entryPoints: ['server.ts'],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  packages: 'external',
  sourcemap: true,
  outfile: 'dist/server.cjs',
  banner: {
    js: `// Github-devy Server Bundle\n// Generated by esbuild\n// DO NOT EDIT DIRECTLY\n\n`
  },
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
  },
  loader: {
    '.ts': 'ts',
    '.tsx': 'tsx'
  },
  logLevel: 'info'
};

console.log('🔧 Building server with esbuild...');
console.log(`   Entry: ${config.entryPoints[0]}`);
console.log(`   Out: ${config.outfile}`);

try {
  await esbuild.build(config);
  console.log('✅ Server built successfully');
  console.log(`   Output: ${path.resolve(__dirname, config.outfile)}`);
  
  const stats = await fs.stat(path.resolve(__dirname, config.outfile));
  console.log(`   Size: ${(stats.size / 1024).toFixed(2)} KB`);
  
  process.exit(0);
} catch (error) {
  console.error('❌ Build failed:');
  console.error(error);
  
  // Provide helpful error messages
  if (error.message.includes('Cannot find module')) {
    console.error('\n💡 Tip: Make sure all dependencies are installed. Try running:');
    console.error('   npm install');
  } else if (error.message.includes('entry point')) {
    console.error('\n💡 Tip: Check that the entry file exists:');
    console.error(`   ls -la ${config.entryPoints[0]}`);
  }
  
  process.exit(1);
}
